# Generated by Django 4.2.4 on 2023-09-03 06:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_app", "0003_tracking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tracking",
            name="tracks",
            field=models.ManyToManyField(
                blank=True, to="django_app.item", verbose_name="Трек код"
            ),
        ),
    ]
